### ISSUE TITLE
Error after splash screen from external lib :)

### ISSUE THREAD

**Issue by HelloMyDevWorld** [DevWizza/Leona-Store#27]
![image](https://user-images.githubusercontent.com/19226186/29239632-30f7501c-7f53-11e7-84fe-32630e731d5d.png)

Error after splash screen from external lib :+1:

**Comment by LuisAlbertoPenaNunez** [comment]
@patsadow2 In order to know how to reproduce the bug can you please detail what did you do exactly to reproduce the bug? I have tested that area of the application and I still haven't run into that bug yet. I understand that it has to do with the cache not finding anything with the given key but:

1) Was it on iOS?
2) Was it your first time running the app?
3) Did you do any changes before running into this?
